### ISSUE TITLE
还是要手动切换开关才生效

### ISSUE THREAD

**Issue by xugui0821** [mengskysama/yikuuuuu#1]
在crontab里4小时运行一次，yiku.status日志里显示提速成功但是网速并没变，手动在网页切换开关再开启提速才有效
switch_mode=1

**Comment by mengskysama** [comment]
4小时太久啦，我改成5分钟了

**Comment by shetz163** [comment]
这个加速应该是有四个小时的时效  过了就会失效
然而  现在好像脚本失效了
提示的是用户未登录
貌似登陆的网址改了
或者是不允许直接访问了
