### ISSUE TITLE
2017.4月最新错误。

### ISSUE THREAD

**Issue by luanshishuma** [mengskysama/yikuuuuu#3]
突然不能加速了。然后一看错误信息，处于不能登陆状态，一直登陆失败，改过密码。

**Comment by suclogger** [comment]
手动请求了一下，可能是这个登陆接口需要验证了
```
jsonp_14811222976476134(
{
errorCode: "NEED_SLIDER_CAPTCHA",
errorMsg: "请拖动下方滑块",
msg: "",
result: "fail"
}
)
```

**Comment by luanshishuma** [comment]
@suclogger 对，需要验证了，不知道有没有解决方法

**Comment by lwl12** [comment]
https://account.youku.com/?callback=https%3A%2F%2Fm.vip.youku.com%2F%3Fc%3Dindex%26a%3Dprivilege_detail%26type%3Dspeed%26spm%3Da2h12.8251612.2408662.8
看起来不用验证码（请带手机UA）

**Comment by luanshishuma** [comment]
可能是我没修改对，用楼上的也不行

**Comment by lwl12** [comment]
。。。这是给作者看的

**Comment by mengskysama** [comment]
@liwanglin12 感谢，到时候我看看·

**Comment by mengskysama** [comment]
@luanshishuma done

**Comment by suclogger** [comment]
果然是有生之年系列。。感谢~

**Comment by lwl12** [comment]
其实刚刚试了下还是登不上（
